'use strict';
const $ = id => document.getElementById(id);
const pageNames = {studio:'语音工作室',models:'模型管理',voices:'我的声音',history:'生成记录',environment:'环境与帮助'};
let state = {models:[],voices:[],jobs:[]}, mode = 'base', busy = false, job = null, audio = null, initialized = false, logs = '', toastTimer, selectedVoiceName = '', segmentDrafts = {};
const valueKeys = ['language','speaker','instruction','referenceText','rate','volume','segmentLength','gap','temperature','topP','topK','repetition','seed','maxTokens','threads','quantization','maxReference'];
const numericKeys = new Set(['rate','volume','segmentLength','gap','temperature','topP','topK','repetition','seed','maxTokens','threads','maxReference']);
function send(action,data={}){if(window.webkit && window.webkit.messageHandlers && window.webkit.messageHandlers.studio){window.webkit.messageHandlers.studio.postMessage({action,data});}else{toast('预览模式：文件选择、下载与生成需要从声笺 Mac 应用运行。');}}
function toast(message,error=false){clearTimeout(toastTimer);$('toast').textContent=message;$('toast').className=error?'error':'';$('toast').hidden=false;toastTimer=setTimeout(()=>{$('toast').hidden=true;},error?18000:5000);}
function page(name){document.querySelectorAll('.page').forEach(e=>e.classList.toggle('active',e.id==='page-'+name));document.querySelectorAll('.nav').forEach(e=>e.classList.toggle('active',e.dataset.page===name));$('pageName').textContent=pageNames[name];document.querySelector('.content').scrollTop=0;}
function element(tag,className,text){const el=document.createElement(tag);if(className)el.className=className;if(text!==undefined)el.textContent=text;return el;}
function button(text,callback,className='button'){const el=element('button',className,text);el.addEventListener('click',callback);return el;}
function clock(seconds){seconds=Math.max(0,Math.floor(seconds||0));return Math.floor(seconds/60).toString().padStart(2,'0')+':'+(seconds%60).toString().padStart(2,'0');}
function activeSpec(){return state.models.find(m=>m.id===$('modelSelect').value);}
function getSettings(){const result={modelId:$('modelSelect').value,xvector:$('xvector').checked};valueKeys.forEach(key=>{result[key]=numericKeys.has(key)?Number($(key).value):$(key).value;});if($('instruction').disabled)result.instruction='';let advanced;try{advanced=JSON.parse($('advanced').value||'{}');}catch(e){throw Error('高级参数不是有效 JSON。');}if(!advanced||Array.isArray(advanced)||typeof advanced!=='object')throw Error('高级参数必须是 JSON 对象。');result.advanced=advanced;return result;}
function guarded(fn){return ()=>{try{fn();}catch(e){toast(e.message,true);}};}
function applySettings(settings){valueKeys.forEach(key=>{if(settings[key]!==undefined)$(key).value=settings[key];});$('xvector').checked=!!settings.xvector;$('advanced').value=JSON.stringify(settings.advanced||{},null,2);const spec=state.models.find(m=>m.id===settings.modelId);if(spec){mode=spec.kind;renderModelSelect(spec.id);}updateSliders();}
function renderModelSelect(preferred){const old=preferred||$('modelSelect').value;$('modelSelect').textContent='';state.models.filter(m=>m.kind===mode).forEach(m=>{const option=element('option',null,m.size+' · '+(m.installed?'已就绪':'未安装'));option.value=m.id;$('modelSelect').appendChild(option);});if(Array.from($('modelSelect').options).some(o=>o.value===old))$('modelSelect').value=old;updateMode();}
function updateMode(){document.querySelectorAll('[data-mode]').forEach(e=>e.classList.toggle('selected',e.dataset.mode===mode));$('referenceCard').hidden=mode==='voice_design';$('speakerField').hidden=mode!=='custom_voice';$('instructionField').hidden=mode==='base';const spec=activeSpec();$('instructionLabel').textContent=mode==='voice_design'?'描述想要的声音（必填）':'风格指令（1.7B）';$('instruction').disabled=mode==='custom_voice'&&spec&&spec.size==='0.6B';$('modelHint').textContent=spec&&spec.installed?'✓ 本地模型可用 · CPU 推理': '模型尚未安装。请先下载或导入。';$('goModels').hidden=!!(spec&&spec.installed);$('saveVoice').disabled=busy||mode!=='base';$('xvector').disabled=busy||mode!=='base';}
function updateSliders(){$('rateValue').textContent=Number($('rate').value).toFixed(2)+'×';$('volumeValue').textContent=Number($('volume').value).toFixed(2)+'×';}
function renderModels(){const container=$('modelGrid');container.textContent='';state.models.forEach(m=>{const card=element('article','card model-card'),top=element('div','card-top');top.appendChild(element('span','model-symbol',m.kind==='base'?'◎':m.kind==='voice_design'?'✧':'◉'));top.appendChild(element('span','badge'+(m.installed?'':' muted'),m.installed?'已就绪':'未安装'));card.appendChild(top);card.appendChild(element('h3',null,m.name));card.appendChild(element('p',null,m.kind==='base'?'从本人录音克隆声音，支持保存声音档案。':m.kind==='voice_design'?'通过自然语言描述设计一个新的声音。':'9 种预设声音；1.7B 支持风格与情绪指令。'));card.appendChild(element('div','path',m.path||m.repo));const action=button(m.installed?'在工作室使用 ↗':'下载模型 ↓',()=>{if(m.installed){mode=m.kind;renderModelSelect(m.id);page('studio');}else send('download',{id:m.id,source:$('downloadSource').value});});action.disabled=busy;card.appendChild(action);container.appendChild(card);});$('modelCount').textContent=state.models.filter(m=>m.installed).length;}
function renderVoices(){const selected=selectedVoiceName||$('voiceSelect').value;$('voiceSelect').textContent='';const empty=element('option',null,'不使用保存的声音');empty.value='';$('voiceSelect').appendChild(empty);const grid=$('voicesGrid');grid.textContent='';state.voices.forEach(v=>{const option=element('option',null,v.name);option.value=v.name;$('voiceSelect').appendChild(option);const card=element('article','card model-card');card.appendChild(element('div','model-symbol','◎'));card.appendChild(element('h3',null,v.name));card.appendChild(element('p',null,v.name.endsWith('.bin')?'音色向量档案 · 本地保存':'完整克隆提示 · 社区 graft 格式'));card.appendChild(button('在工作室使用 ↗',()=>{send('selectVoice',{name:v.name});page('studio');if(mode==='voice_design'){mode='base';renderModelSelect();}}));grid.appendChild(card);});if(!state.voices.length)grid.appendChild(element('div','empty-state','还没有保存的声音。\n在工作室选择录音和 Base 模型，点击“保存当前声音”。'));if(Array.from($('voiceSelect').options).some(o=>o.value===selected))$('voiceSelect').value=selected;}
function statusName(status){return {done:'已完成',running:'生成中',pending:'待生成',cancelled:'已取消',failed:'失败',partial:'部分完成'}[status]||status;}
function renderHistory(){const list=$('historyList');list.textContent='';state.jobs.forEach(j=>{const item=element('article','history-item'),copy=element('div','history-copy');copy.appendChild(element('strong',null,j.title));copy.appendChild(element('small',null,new Date(j.created).toLocaleString()+' · '+j.count+' 段'));item.appendChild(element('span','model-symbol','◷'));item.appendChild(copy);item.appendChild(element('span','badge'+(j.status==='done'?'':' warning'),statusName(j.status)));item.appendChild(button('打开项目',()=>send('loadJob',{id:j.id}),'button subtle'));list.appendChild(item);});if(!state.jobs.length)list.appendChild(element('div','empty-state','第一段声音，从这里开始。\n生成完成或取消后的项目都会保存在这里。'));}
function renderEnvironment(){const env=state.environment||{},grid=$('environmentGrid');grid.textContent='';const entries=[['操作系统',env.os||'检测中','编译目标：macOS 10.15+'],['处理器',env.arch||'—',(env.cores||0)+' 个逻辑处理器'],['内存',env.memoryGB?env.memoryGB.toFixed(0)+' GB':'—','先用 0.6B 短句测试'],['可用空间',env.freeGB?env.freeGB.toFixed(1)+' GB':'—','下载前会再次检查空间'],['运行环境',env.ready?'已就绪':'未就绪',env.message||'正在准备原生引擎'],['运行方式','CPU / Accelerate','无需 Docker、Python 或 NVIDIA 驱动']];entries.forEach(([label,value,note])=>{const card=element('div','card env-item');card.appendChild(element('small',null,label));card.appendChild(element('strong',null,value));card.appendChild(element('span',null,note));grid.appendChild(card);});$('environmentBadge').textContent=env.ready?'● 本地引擎就绪':'环境尚未就绪';$('environmentBadge').className='badge'+(env.ready?'':' warning');}
function renderJob(next){job=next;$('segmentsCard').hidden=false;$('segmentStatus').textContent=statusName(job.status);$('segments').textContent='';(job.segments||[]).forEach((segment,index)=>{const card=element('div','segment'),head=element('div','segment-header');head.appendChild(element('span',null,'第 '+(index+1).toString().padStart(2,'0')+' 段'));head.appendChild(element('span',null,statusName(segment.status)+(segment.duration?' · '+clock(segment.duration):'')));card.appendChild(head);const text=element('textarea');text.value=segmentDrafts[job.id+':'+index]===undefined?segment.text:segmentDrafts[job.id+':'+index];text.addEventListener('input',()=>{segmentDrafts[job.id+':'+index]=text.value;});text.setAttribute('aria-label','第 '+(index+1)+' 段文本');text.disabled=busy;card.appendChild(text);const actions=element('div','segment-actions');const listen=button('试听',()=>send('previewSegment',{id:job.id,index}),'button subtle');listen.disabled=busy||segment.status!=='done';const redo=button(segment.status==='done'?'重生成此段':'生成此段',guarded(()=>{const settings=getSettings(),draft=text.value;delete segmentDrafts[job.id+':'+index];send('regenerate',{id:job.id,index,text:draft,settings});}));redo.disabled=busy;actions.appendChild(listen);actions.appendChild(redo);card.appendChild(actions);$('segments').appendChild(card);});}
function drawWaveform(values){const canvas=$('waveform'),ctx=canvas.getContext('2d');ctx.clearRect(0,0,canvas.width,canvas.height);const n=values&&values.length?values.length:100;const width=canvas.width/n;for(let i=0;i<n;i++){const height=values&&values.length?Math.max(2,Math.min(1,values[i])*80):2;ctx.fillStyle=values&&values.length?'#8fa87b':'#e0e7d6';ctx.fillRect(i*width+1,(canvas.height-height)/2,Math.max(1,width-3),height);}}
function setBusy(value){busy=!!value.active;$('generate').disabled=busy;$('cancel').hidden=!busy;$('progressContainer').hidden=!busy;$('taskLight').classList.toggle('working',busy);$('taskTitle').textContent=busy?value.title:'准备就绪';if(!busy)$('taskDetail').textContent='任务结果请查看工作区或诊断日志';else{$('taskDetail').textContent='正在本机处理，请稍候';$('progressFill').style.width='0%';}document.querySelectorAll('.settings-card input,.settings-card select,.settings-card textarea,.mode-tabs button,#chooseReference,#importText,#importModel,#downloadSource,#importVoice,#voiceSelect,#saveSettings').forEach(el=>{el.disabled=busy;});renderModels();updateMode();if(job)renderJob(job);$('applyEdit').disabled=busy||!audio;}
window.receiveNative=function(event){const data=event.data;switch(event.topic){case 'state':state=data;renderModelSelect();renderModels();renderVoices();renderHistory();renderEnvironment();if(!initialized){$('downloadSource').value=state.downloadSource||'modelscope';applySettings(state.settings||{});initialized=true;}break;case 'busy':setBusy(data);break;case 'progress':$('taskDetail').textContent=data.label;$('progressFill').style.width=Math.max(0,Math.min(100,data.fraction*100))+'%';break;case 'notice':toast(data);break;case 'error':toast(data,true);$('taskTitle').textContent='请检查任务结果';$('taskDetail').textContent=String(data).split('\n')[0];break;case 'log':logs+=data;logs=logs.slice(-50000);$('diagnosticLog').textContent=logs;$('diagnosticLog').scrollTop=$('diagnosticLog').scrollHeight;break;case 'text':$('text').value=data.text;$('documentName').textContent=data.name;updateCount();page('studio');break;case 'reference':$('referenceInfo').textContent='';const icon=element('span','mic-icon','✓'),copy=element('div');copy.appendChild(element('strong',null,data.name));copy.appendChild(element('p',null,clock(data.duration)+' · 已转换为 24kHz 单声道 WAV'));$('referenceInfo').appendChild(icon);$('referenceInfo').appendChild(copy);break;case 'voice':selectedVoiceName=data.name||'';if(data.name){$('voiceInfo').textContent='正在使用：'+data.name;if(Array.from($('voiceSelect').options).some(o=>o.value===data.name))$('voiceSelect').value=data.name;}else{$('voiceInfo').textContent='没有选择保存的声音，使用当前参考录音。';$('voiceSelect').value='';}break;case 'job':if(!job||job.id!==data.id){applySettings(data.settings||{});$('text').value=(data.segments||[]).map(s=>s.text).join('\n\n');$('documentName').textContent=data.title;updateCount();page('studio');}renderJob(data);break;case 'audio':audio=data;$('audioName').textContent=data.name;$('audioDuration').textContent=clock(data.duration);$('seek').max=data.duration;$('seek').value=0;$('seek').disabled=false;$('play').disabled=false;$('exportAudio').disabled=false;$('applyEdit').disabled=busy;$('trimStart').value=0;$('trimEnd').value=0;drawWaveform(data.waveform);break;case 'playback':$('play').textContent=data.playing?'Ⅱ':'▶';$('seek').value=data.time;$('playTime').textContent=clock(data.time);break;}}
function updateCount(){$('charCount').textContent=Array.from($('text').value).length.toLocaleString()+' 字';}
document.querySelectorAll('[data-page]').forEach(el=>el.addEventListener('click',()=>page(el.dataset.page)));
document.querySelectorAll('[data-mode]').forEach(el=>el.addEventListener('click',()=>{mode=el.dataset.mode;renderModelSelect();}));
$('modelSelect').addEventListener('change',updateMode);$('text').addEventListener('input',updateCount);['rate','volume'].forEach(id=>$(id).addEventListener('input',updateSliders));
const actions={importText:'importText',chooseReference:'reference',importModel:'importModel',importVoice:'importVoice',checkEnvironment:'check',folderButton:'openFolder',openSupport:'openSupport',cancel:'cancel',play:'play',exportAudio:'export',refreshHistory:'refresh'};Object.keys(actions).forEach(id=>$(id).addEventListener('click',()=>send(actions[id])));
$('goModels').addEventListener('click',()=>page('models'));$('voiceSelect').addEventListener('change',()=>send($('voiceSelect').value?'selectVoice':'clearVoice',{name:$('voiceSelect').value}));
$('sampleText').addEventListener('click',()=>{if($('text').value.trim()){toast('文稿已有内容，未覆盖。请先清空后再填入测试文稿。');return;}$('text').value='你好，欢迎来到我的声音工作室。\n这段语音将在我的电脑上生成，让文字拥有自己的温度。';updateCount();});
$('generate').addEventListener('click',guarded(()=>{const spec=activeSpec();if(!spec||!spec.installed){page('models');throw Error('请先下载或导入一个模型。');}if(!$('text').value.trim())throw Error('请先输入或导入文稿。');send('generate',{text:$('text').value,settings:getSettings()});}));
$('saveSettings').addEventListener('click',guarded(()=>send('saveSettings',getSettings())));
$('saveVoice').addEventListener('click',guarded(()=>send('saveVoice',{name:'我的声音',settings:getSettings()})));
$('seek').addEventListener('change',()=>send('seek',{seconds:Number($('seek').value)}));
$('applyEdit').addEventListener('click',()=>send('editAudio',{start:Number($('trimStart').value),end:Number($('trimEnd').value),gain:Number($('editGain').value),rate:Number($('editRate').value),pitch:Number($('editPitch').value),fade:Number($('editFade').value),normalize:$('normalize').checked}));
$('toast').addEventListener('click',()=>{$('toast').hidden=true;});drawWaveform([]);send('ready');
